### ISSUE TITLE
error with calculate_frustration function

### ISSUE THREAD

**Issue by dkssudgktpdy03** [proteinphysiologylab/frustratometeR#5]
Dear Dev Team,

i'm trying to follow your 'Example.R' code with 1n0r.pdb file which you uploaded.

then, when I run this code
```
PdbFile <- "C:/R_project/R_project/1n0r.pdb"
ResultsDir <- "C:/R_project/R_project/Results"

dir.create(file.path(ResultsDir))
Pdb_conf <- calculate_frustration(PdbFile = PdbFile, Mode = "configurational", ResultsDir = ResultsDir, Graphics = TRUE)
```
I got this results,

```
> Pdb<-calculate_frustration(PdbFile=PdbFile, Mode = "configurational", ResultsDir = ResultsDir,Graphics = TRUE)
-----------------------------Filtering-----------------------------
-----------------------------Preparing files-----------------------------
-----------------------------Setting options-----------------------------
Error in file(file, open = "r") : cannot open the connection
In addition: Warning message:
In file(file, open = "r") :
  cannot open file '/R_project/R_project/Results/1n0r.done/1n0r.in': No such file or directory

```

actually i check the path on "/R_project/R_project/Results/1n0r.done/" and find out there's no "1n0r.in" files.

I can't figure out what is the problem,,,

**Comment by gonzaparra** [comment]
Can you let us know  your operative system and version?

Can you try running the function that downloads the file instead of reading
the pdbfile locally?

**Comment by dkssudgktpdy03** [comment]
Dear Dev Team,

Thank you for answering me.
Actually I'm very new in using R program, so it took some time to try new
codes.

I'm using window 11, and I use R program version 4.3.1.
And also I used version 3.6.3 as you suggested.

When I download pdbfile instead of reading locally i got below error.
I would be grateful if you could check what should I change.
Thank you for reading  my email.


#############

> library(frustratometeR)> PdbFile <- download.file("https://files.rcsb.org/download/1N0R.pdb", destfile = "1N0R.pdb")

   trying URL 'https://files.rcsb.org/download/1N0R.pdb'downloaded 114 KB

> ResultsDir <- "C:/R_project/FrustratometeR/Result/"
> dir.create(file.path(ResultsDir))> Pdb_conf <- calculate_frustration(PdbFile = PdbFile, Mode = "configurational", ResultsDir = ResultsDir, Graphics = TRUE)

   Error in file.exists(file) : invalid 'file' argument

#############

**Comment by skrhakv** [comment]
Dear @gonzaparra, 

I encountered the same error as @dkssudgktpdy03 when using `Fedora OS` regardless of whether the PDB file is downloaded or whether it is already locally present. When the PDB file is downloaded:
```
> Pdb_conf <- calculate_frustration(PdbID = "1n0r",Chain = "A",  ResultsDir = "/home/vit/Projects/NMA/data/frustration")
-----------------------------Download files-----------------------------
1n0r.pdb.2              [  <=>               ] 114.62K   300KB/s    in 0.4s    
-----------------------------Filtering-----------------------------
-----------------------------Preparing files-----------------------------
Pdb file: 1n0r_A
Output file: 1n0r_A
Traceback (most recent call last):
  File "/home/vit/R/x86_64-redhat-linux-gnu-library/4.2/frustratometeR/Scripts/AWSEMFiles/AWSEMTools/PDBToCoordinates.py", line 134, in <module>
    from Bio.PDB.PDBParser import PDBParser
ModuleNotFoundError: No module named 'Bio'
Traceback (most recent call last):
  File "/home/vit/R/x86_64-redhat-linux-gnu-library/4.2/frustratometeR/Scripts/AWSEMFiles/AWSEMTools/CoordinatesToWorkLammpsDataFile.py", line 111, in <module>
    inp = open(inp_file)
          ^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '1n0r_A.coord'
-----------------------------Setting options-----------------------------
Error in file(file, open = "r") : cannot open the connection
In addition: Warning message:
In file(file, open = "r") :
  cannot open file '/home/vit/Projects/NMA/data/frustration/1n0r_A.done/1n0r_A.in': No such file or directory
```
 When the PDB file is already present:
```
> Pdb_conf <- calculate_frustration(PdbFile = PdbFile, ResultsDir = ResultsDir)
   PDB has ALT records, taking A only, rm.alt=TRUE
-----------------------------Filtering-----------------------------
-----------------------------Preparing files-----------------------------
Pdb file: 1adeA_clean_h
Output file: 1adeA_clean_h
Traceback (most recent call last):
  File "/home/vit/R/x86_64-redhat-linux-gnu-library/4.2/frustratometeR/Scripts/AWSEMFiles/AWSEMTools/PDBToCoordinates.py", line 134, in <module>
    from Bio.PDB.PDBParser import PDBParser
ModuleNotFoundError: No module named 'Bio'
Traceback (most recent call last):
  File "/home/vit/R/x86_64-redhat-linux-gnu-library/4.2/frustratometeR/Scripts/AWSEMFiles/AWSEMTools/CoordinatesToWorkLammpsDataFile.py", line 111, in <module>
    inp = open(inp_file)
          ^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '1adeA_clean_h.coord'
-----------------------------Setting options-----------------------------
Error in file(file, open = "r") : cannot open the connection
In addition: Warning message:
In file(file, open = "r") :
  cannot open file '/home/vit/Projects/NMA/data/frustration/1adeA_clean_h.done/1adeA_clean_h.in': No such file or directory
```
I checked the path and the file `1adeA_clean_h.in` (`1n0r_A.in`) is indeed not there.
My OS is `Fedora release 37`.

Thanks in advance for any assistance. By the way, the library is great, and thank you for making the tool available.

**Comment by gonzaparra** [comment]
Dear @skrhakv,

Your error is different. You get this error: "from Bio.PDB.PDBParser import PDBParser
ModuleNotFoundError: No module named 'Bio'"

That error means that you have not installed biopython or that your R session is not able to find it. You have to configure your session correctly so the R package can communicate with your python dependencies. 

We list the dependencies in the wiki:
https://github.com/proteinphysiologylab/frustratometeR/wiki/2.-Installation

We also give several recommendations here about how to install dependencies:
https://github.com/proteinphysiologylab/frustratometeR

Best,

Gonzalo

**Comment by skrhakv** [comment]
Ohh I missed that. Thank you @gonzaparra for pointing out the true cause of the error. It is working without any problems now.

And thanks for providing this great tool!

Vit
